dist: trusty
notifications:
  email: false
fail_fast: true
language: go
go:
- 1.x
sudo: false
os:
- linux
env:
  secure: DIdDml8gNouBc7Lw6hyOQj0PNKbhfGC0RK3wnF/Vtxz3V0nZJbe4+qFqIariYLhurlHB20QKPlsel28pHbSvR4+SCHPZRD6Id/JfGGmKdHRzlVYpcOAMNoOwqJLcKWoIV00644JerkCkvShA0tqWd1kk9NkWAkIMLV1l1KdGZsQySgPFNNbhcRuidDN74zE49Wl6iR1rEZR3veN0aoaRvMUCKZQFDDquS9J8E98lkTKIOFObDLwopCO0sTQ23UbknBhxaCRkDBKyty+GgsV4OhoFMpmh985l+KqLNdKsjGu0M34lXi2wx+eK7H1VfJbYnU3dImbOvyuJMCYQBf62kLW1h84WwpWNfnSd+ZTVN8LwZeyWxHUFHBmPC5D8qsfIW254GxxuNwH+g5t3Si6BIGgVZ8qaFHNpcvBba8mTSwt+6+w3PJWFqbqPdyjJ6+uSsBINkHpsphF066dn6eSNRQu5f5n0lcOqQt1zcyvI4yi9s40l/kisGpGcU/jXzLRaOhJz1lTvU7fmtv16UmAwVN88ZoOZ4Dj6WImJIt4PBq7qAIKGKlbFV7OnIGWeYgpKFr4AcZUU7fMC8QMypHf0V3xf0skwtlvtEIse7F0pXAMFjPYfJmp9JG2QNCnLHP/y4eoUtD6Eu7/Cq33Z8uFDxYnlb1lRsXEU2sl5+NvbhOM=
addons:
  postgresql: '9.5'
install:
- go get -u github.com/golang/lint/golint
before_script:
- psql -c 'create database feedsys;' -U postgres
- psql -c "CREATE USER bigbang WITH PASSWORD 'bigbang';" -U postgres
- psql -c "ALTER USER bigbang WITH SUPERUSER;" -U postgres
before_install:
- V=0.20.0
- OS=linux
- URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
- wget -O install.sh "${URL}"
- chmod +x install.sh
- "./install.sh --user"
- rm -f install.sh
script:
- bazel clean
- bazel run //:gazelle
- bazel test --config=ci  //test/integration/...
