dist: trusty
notifications:
  email: false
fail_fast: true
language: go
go:
- 1.x
sudo: false
os:
- linux
addons:
  postgresql: '9.5'
install:
- go get -u github.com/golang/lint/golint
before_script:
- psql -c 'create database feedsys;' -U postgres
- psql -c "CREATE USER bigbang WITH PASSWORD 'bigbang';" -U postgres
- psql -c "ALTER USER bigbang WITH SUPERUSER;" -U postgres
before_install:
- V=0.20.0
- OS=linux
- URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
- wget -O install.sh "${URL}"
- chmod +x install.sh
- "./install.sh --user"
- rm -f install.sh
script:
- bazel clean
- bazel run //:gazelle
- bazel test --config=ci  //test/integration/...
env:
  global:
    secure: o7H4pkgfexYHHhR3ko6PqHF5qeGcJTLrSl4jQTBcoe5WeWd+GmWDrL6/yYox9LCE3x1EpNAY5aj4ZQ+J+pXE+E4t+C4aPmeMmCxdKwocsX8YcTnlL8wNh3Xq2HTEhr4THO4SHIMaLQDxyUQy5EKUdk1eJT2U976fNBJoq27VCS1hoVqS/KCN+XWwXKKK/zLT3v3GqoD4EisMxmOy+DLV+s16km5SJ4aBSqa19LWskdcOQjDs2wfru4x9vrOI+Bo0JLoGTk6KDQUd4rHco0ArAdPgsXvq17IcAQBbrKB24RtY3oVc3qrbCgZDH2I9W/us0jha/3V7GnbC5qaajimfBtNJf3pKDvH5avcKrujJfc2q+7jIf4+VW7yDI+C+YY33qsH1LCTFEsM2/pQGIc1OjdoVJvX/ePEjIRCVYLw3Mee+7TkQA4z2hG6Y502by+l7YU2ZIKgQO3pf/LoCdYVmOjyWGz5TMjey77HGgxsCtnCM/2Hl+SU06/D34MbHqIJG99CZBoFPtN/boUpX3g9cqcf5Q6pPrvdZm3Eohu8QK/qsjgGtXI/QJ0UBnOB2NTkI6ABeg0ASI9GsyHItaUkKl/l1KFnUru/NCKOEeccB8qKVDTwvVc0j/VwGSwTfxA2UgnzadMQW/kT6lpeQHjrGjHVzLvzKHOIfa6QJ6s8WjJk=
