# trusty beta image has jdk8, gcc4.8.4
dist: trusty
notifications:
  slack: ventureum-team:DSE8wxmLTenq0Yz17BrYBWg9
fail_fast: true

language: go
go:
  - 1.x
sudo: false

os:
  - linux

env:
  secure: "eh8ENEz7aT3qdwOj5n5fz//UpWWC74WR7z1YjNTPG6qgVvZloSX29esfZPTR26SLu0kcPT3VwsTHuEY1GvFBZucZb4KT17EQS0pEtqJogGZnxeEz87oivHqGPadVmfYSNJ1Z5zz2P0mb/pexkdGiTejpcUEJW3v5Ybq5ZwhsfeVhBXIaCs9ba3mHgpeWa6M4aKSFjhG5GHnPVvWVbtBBRMsb/tcA74n0LabSavFbE0kTiEFPhiSFaV31mwyS662AnbJFJg/1IDr+iyacx65Km+5Od8d8HCdmpIM0uAJ2OLkXpU+bekuDYCzCHfGlOnC5aBppaYj6esmtDzgS+YmlctjBi5j5B8WaE+K+ePTbPttNsBW8FWCbW0b2HOUEiC1hu26gMx0mQFQqYQyIgbAWMA8DywfreHXwCee+AJPXFf35n5MpHarFDvfwwjWuA/UZCB5kft9EPbL3BE+GNjbTiLgwmS2m3BuSdewRtRUoaeCtV1K0ubjsEmENhEMuhGllK+MmpnYcIMpPbBdK4FrYigRb3oO2KG+VjpGP1K1I6dmzsjUYDP0sOSn6YSRUMJ9zuvLWprz2fz1hf6AYmbj0c0z9IhaL5bCzVi6+fykW5XsQJ2h5W0zvHb+s/GUic5Nr8dmCoiDuZuNxQq5uFwL3czrcEohqPSST7B/ZiG/jLW8="
addons:
  postgresql: "9.5"

install:
- go get -u github.com/golang/lint/golint


before_script:
- psql -c 'create database feedsys;' -U postgres
- psql -c "CREATE USER bigbang WITH PASSWORD 'bigbang';" -U postgres
- psql -c "ALTER USER bigbang WITH SUPERUSER;" -U postgres

before_install:
- V=0.20.0
- OS=linux
- URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
- wget -O install.sh "${URL}"
- chmod +x install.sh
- ./install.sh --user
- rm -f install.sh

script:
# enable golint after further cleaning
# - 'golint ./... | grep -v "be unexported"'
- bazel clean
- bazel run //:gazelle
- bazel test --config=ci  //test/integration/...

notifications:
  email: false
